apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: "5.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    qbittorrent:
      env:
        TZ: "America/New_York"
        PUID: "8675309"
        PGID: "8675309"
      ingress:
        enabled: true
        hosts:
          - host: qb.kube.com
            paths:
              - path: /
                pathType: Prefix