---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v2\.[0-9]+\.[0-9]+-ls[0-9]+)$'
spec:
  releaseName: tautulli
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: tautulli
    version: 3.0.1
  values:
    image:
      repository: linuxserver/tautulli
      tag: v2.5.6-ls14
timezone: "America/New_York"
puid: 1000
pgid: 1000

service:
  type: LoadBalancer
  port: 8181
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster

persistence:
      config:
        enabled: true
        existingClaim: nfs-data-pvc        