
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: system
  labels:
    app: traefiklabs
    name: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: system

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami
    
---
#trying ingress

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute
  namespace: default

spec:
  entryPoints:
    - web

  routes:
  - match: Host(`whoami.kube.com`) || Host(`whoami`)
    kind: Rule
    services:
    - name: whoami
      port: 80    