---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      version: "0.0.14"
      sourceRef:
        kind: HelmRepository
        name: naps
        namespace: flux-system
      interval: 1m
  values:   
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - "/mnt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi    