ignore: |
  .yamllint.yaml
  .github/
  flux-system
  system-apps/local-storage.yaml
  deployments/zz_generated_secrets.yaml
  system-apps/kube-dash.yaml
extends: default
rules:
  truthy:
    allowed-values: ["true", "false", "on", "yes"]
  comments:
    min-spaces-from-content: 1
  line-length: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: consistent
