---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: "6.0"
    # UID: 1024
    # GID: 1024
    ingress:
      enabled: true
      hosts:
        - unifi.kube.com
    controllerService:
      type: LoadBalancer
    stunService:
      type: LoadBalancer
    guiService:
      type: ClusterIP
    discoveryService:
      type: LoadBalancer
    persistence:
      storageClass: "local-path"
    resources:
      limits:
        cpu: 1000m
        memory: 1500Mi
      requests:
        cpu: 20m
        memory: 300Mi