---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "America/New_York"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      enabled: true
      hosts:
      - host: jackett.kube.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "jackett.kube.com"    
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: "1Gi"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi