---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      version: "2.1.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    timezone: "America/New_York"
    plexUid: "8675309"
    plexGid: "8675309"
    ingress:
      enabled: true
      hosts:
        - plex.kube.com
      path: /
    persistence:
      config:
        enabled: true
        size: 1Gi
      transcode:
        enabled: false
      data:
        enabled: false