---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "America/New_York"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      enabled: true
      hosts:
      - host: qb.kube.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "qb.kube.com"
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        path: /mnt
        size: 1Gi
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi    