---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: "7.0.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    controllerType: deployment
    env:
      TZ: "America/New_York"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      enabled: true
      hosts:
        - host: radarr.kube.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: "/config"
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        path: /mnt
        size: 1Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: "/mnt/media"
    addons:
      vpn:
        enabled: false