---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission-openvpn
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: transmission-openvpn
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: transmission-openvpn
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "America/New_York"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      enabled: true
      hosts:
      - host: transmission.kube.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "transmission.kube.com"
    persistence:
      data:
        enabled: true
        storageClass: "local-path"
        accessModes: 
          -ReadWriteOnce        
        size: "1Gi"      
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi