---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 1.2.0
  valuesFrom:
  - externalSourceRef:
      url: https://github.com/zenxedo/k3s-gitops/blob/master/flux/flux-helm-operator-values.yaml