apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik-external"    
        hosts:
          - "who.kube.com"  
    jackett:
      env:
        TZ: America/New_York
    
      
   
