---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: "6.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true     
      hosts:
        - sonarr.kube.com
    sonarr:
      env:
       # TZ: America/New_York
       # puid: 1000
       # pgid: 1000