apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tautulli
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    tautulli:
      env:
        TZ: America/New_York
      service:
        type: LoadBalancer
        port: 8181  