---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v2\.[0-9]+\.[0-9]+-ls[0-9]+)$'
spec:
  releaseName: tautulli
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: tautulli
    version: 3.0.1
  values:
    image:
      repository: linuxserver/tautulli
      tag: v2.5.6-ls14
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    service:
      type: LoadBalancer
      port: 8181
    persistence:
      config:
        enabled: true
        existingClaim: nfs-data-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi        

      